site_name: 图灵班学习指南
site_url: https://ZJU-Turing.github.io/TuringCourses/
site_description: 图灵班学习指南
repo_name: ZJU-Turing/TuringCourses
repo_url: https://github.com/ZJU-Turing/TuringCourses/
edit_uri: tree/master/docs
copyright: Copyright &copy; 2023-2024 浙江大学图灵班

nav:
  - 主页:
    - index.md
    - 贡献指南: contributing.md
    - 课程页面模板: template.md
    - 更新历史: changelog.md
  - 思政军体课:
    - political/index.md
    - 形势与政策 Ⅰ: political/situation_policy1/index.md
    - 思想道德与法治: political/morality_law/index.md
    - 中国近现代史纲要（H）: political/modern_history/index.md
    - 马克思主义基本原理（H）: political/marxism_basic/index.md
    - 毛泽东思想和中国特色社会主义理论体系概论（H）: political/mao_thought/index.md
    - 习近平新时代中国特色社会主义思想概论: political/xi_thought/index.md
    - 形势与政策 Ⅱ: political/situation_policy2/index.md
    - 军事理论: political/military_theory/index.md
  - 通识选修课:
    - general/index.md
    - 通识核心课: general/core.md
    - 通识选修课: general/elective.md
    - 其他选修课: general/others.md
  - 数理基础课:
    - math_phys/index.md
    - 线性代数 Ⅰ（H）: math_phys/linear_algebra1/index.md
    - 线性代数 Ⅱ（H）: math_phys/linear_algebra2/index.md
    - 数学分析（甲）Ⅰ（H）: math_phys/math_analysis1/index.md
    - 数学分析（甲）Ⅱ（H）: math_phys/math_analysis2/index.md
    - 普通物理学 Ⅰ（H）: math_phys/physics1/index.md
    - 普通物理学 Ⅱ（H）: math_phys/physics2/index.md
    - 普通物理学实验 Ⅰ（H）: math_phys/physics_experiment1/index.md
    - 普通物理学实验 Ⅱ（H）: math_phys/physics_experiment2/index.md
    - 概率论（H）: math_phys/probability/index.md
  - 专业基础课:
    - major_basic/index.md
    - 程序设计与算法基础: major_basic/programming/index.md
    - 网络空间安全导论: major_basic/cyberspace_security/index.md
    - 离散数学理论基础: major_basic/discrete_math/index.md
    - 人工智能引论: major_basic/ai_basic/index.md
    - 数据结构基础: major_basic/data_structure/index.md
    - 高级数据结构与算法分析: major_basic/advanced_data_structure/index.md
    - 计算机逻辑设计基础: major_basic/logic_design/index.md
    - 计算机组成与设计: major_basic/computer_organization/index.md
    - 面向对象程序设计: major_basic/object_oriented_programming/index.md
    - 理论计算机科学导引: major_basic/theory_of_computation/index.md
    - 优化基本理论与方法: major_basic/convex_optimization/index.md
    - 操作系统原理与实践: major_basic/operating_system/index.md
    - 计算机系统 Ⅰ: major_basic/computer_system1/index.md
    - 计算机系统 Ⅱ: major_basic/computer_system2/index.md
    - 计算机系统 Ⅲ: major_basic/computer_system3/index.md
  - 专业必修课:
    - major_mandatory/index.md
    - 数据库系统: major_mandatory/database/index.md
    - 计算机网络: major_mandatory/computer_networks/index.md
    - 计算机体系结构: major_mandatory/computer_architecture/index.md
    - 软件工程: major_mandatory/software_engineering/index.md
    - 编译原理: major_mandatory/compilers_principles/index.md
    - 认知神经科学: major_mandatory/cognitive_neuroscience/index.md
    - 机器学习: major_mandatory/machine_learning/index.md
    - 人工智能伦理与安全: major_mandatory/ai_ethics_security/index.md
    - 人工智能实践: major_mandatory/ai_practice/index.md
    - 计算机视觉导论: major_mandatory/computer_vision/index.md
    - 设计认知与设计智能: major_mandatory/design_cognition/index.md
    - 人工智能芯片与系统: major_mandatory/ai_chips_systems/index.md
    - 自然语言处理导论: major_mandatory/natural_language_processing/index.md
    - 汇编语言: major_mandatory/assemble/index.md
    - 密码学: major_mandatory/cryptography/index.md
    - 数据安全与隐私保护: major_mandatory/data_security/index.md
    - 软件安全原理和实践: major_mandatory/software_security/index.md
    - 网络安全原理与实践: major_mandatory/network_security/index.md
    - 人工智能安全: major_mandatory/ai_security/index.md
    - 无线与物理网安全基础: major_mandatory/wireless_iot_security/index.md
    - 系统安全原理和实践: major_mandatory/system_security/index.md
  - 专业模块课:
    - major_module/index.md
    - 数值分析: major_module/numerical_analysis/index.md
    - 应用运筹学基础: major_module/applied_operations_research/index.md
    - 编程语言原理: major_module/principle_of_programming_languages/index.md
    - 计算机科学思想史: major_module/history_of_cs_ideas/index.md
    - 数据挖掘导论: major_module/data_mining/index.md
    - 汇编与接口: major_module/assembly_interface/index.md
    - 嵌入式系统: major_module/embedded_system/index.md
    - 并行计算与多核编程: major_module/parallel_computing/index.md
    - 计算机系统综合实现: major_module/system_comprehensive_practice/index.md
    - 分布式计算: major_module/distributed_computing/index.md
    - 大数据存储与计算技术: major_module/big_data_storage/index.md
  - 专业选修课:
    - major_elective/index.md
    - 技术沟通: major_elective/technology_communication/index.md
    - 图像信息处理: major_elective/digital_image_processing/index.md
    - 脑启发人工智能导论: major_elective/brain_inspired_ai/index.md
    - 人工智能逻辑: major_elective/ai_logic/index.md
    - 计算摄影学: major_elective/computational_photography/index.md
    - 计算机视觉: major_elective/computer_vision/index.md
  - 短学期课程:
    - short_term/index.md
    - 固定课程:
      - short_term/index.md
      - 计算机系统概论: short_term/ics/index.md
      - 工程实践: short_term/engineering_practice/index.md
    - 课程综合实践 Ⅰ:
      - short_term/index.md
      - 超算实训: short_term/hpc/index.md
      - 算法竞赛集训: short_term/acm/index.md
      - 安全攻防实践: short_term/ctf/index.md
      - 大数据可视化: short_term/data_visualization/index.md
    - 课程综合实践 Ⅱ:
      - short_term/index.md
      - C++ 项目管理及工程实践: short_term/cpp_project/index.md
      - Rust 开发实训: short_term/rust/index.md
  - 跨专业课程:
    - others/index.md
    - 常微分方程: others/ode/index.md
    - 数值代数: others/numerical_linear_algebra/index.md
    - 数据建模与分析: others/data_modeling_and_analysis/index.md
    - 抽象代数: others/abstract_algebra/index.md
    - 数论导引: others/number_theory/index.md
    - 经济学类课程集: others/economics/index.md
    - 金融学类课程集: others/finance/index.md
    - B/S 体系软件设计: others/browser_server_software/index.md
    - 电子工程训练: others/electronic_engineering_training/index.md
  - 书评专区:
    - readings/index.md

theme:
  name: 'material'
  language: 'zh'
  # logo: images/icon.png
  icon:
    logo: material/notebook-outline
    repo: fontawesome/brands/github
    edit: material/pencil
  custom_dir: overrides
  favicon: images/icon.png
  features:
    - content.code.annotate
    - content.action.edit
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - navigation.sections
  font:
    # text: Noto Serif SC
    code: JetBrains Mono
  palette:
    - scheme: default

plugins:
  - search
  - heti:
      extra_skipped_class:
        - arithmatex
  - turing_changelog
  - turing_contributors
  - turing_evaluations
  - turing_outdate_warning

extra_css:
  - https://fonts.googleapis.com/css?family=Noto+Serif+SC:300,300i,400,400i,700,700i&display=fallback
  - css/tasklist.css
  - css/card.css
  - css/custom.css

extra_javascript:
  - js/katex.js

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
